### PR TITLE
Fix test failure on mruby-2.0.1.

### PR DESCRIPTION
**Pull request by Shokuji**

### CODE REVIEW

**Comment by mattn** [comment]
What do you want to fix?

**Comment by Shokuji** [comment]
Since the test before correction can not test the error, I changed the test content.

**Comment by take-cheeze** [comment]
(2.0.1 isn't released yet so you should say it's master of mruby/mruby)
BTW this doesn't relate to mruby version. See: https://github.com/mattn/mruby-onig-regexp/issues/91

This change is reasonable so 👍

**Comment by take-cheeze** [comment]
Sorry for forgetting this.
LGTM so merged!

**Pull request merged**
