### PR TITLE
Bundle onigmo and link object files in libonig.a when bundled.

### PR DESCRIPTION
**Pull request by take-cheeze**
(See https://twitter.com/take_cheeze/status/640687184723341312 for discussion.)

Now includes onigmo and adds `bundle_onigmo` singleton method to mrbgem spec.
When "oniguruma.h" isn't found onigmo would be bundled.
if you need to bundled it explicitly call it like `gem(:mgem => "onig-regexp") {|g| g.bundle_onigmo }`.

Fixes build of oniguruma too.
Some flags aren't defined in oniguruma.

When bundled, object files in libonig.a is extracted and linked to libmruby.a directly.

@kazuho Is there any other improvements I can do?

### CODE REVIEW

**Comment by mattn** [comment]
enabled travis-ci for mruby-onig-regexp just now.

https://travis-ci.org/take-cheeze/mruby-onig-regexp

**Comment by mattn** [comment]
ah, my travis.yml are legacy configuration. it should works with merging this pull-request.

**Comment by kazuho** [comment]
@take-cheeze Thank you for the changes!  Will try it out.

**Comment by mattn** [comment]
I think this change is required for mruby-onig-regexp even though if h2o doesn't use this. :) so merged.

**Comment by take-cheeze** [comment]
@mattn Thanks for the merge. :-)

**Comment by kazuho** [comment]
FWIW in H2O I have started using mruby-onig-regexp with https://github.com/kazuho/mruby-onig-regexp/commit/6699ed4026ee043ab1be88f1966fa8a301185d19 applied.

I assume the life would become bit easier if Onigmo could be bundled untared (see https://github.com/kazuho/mruby-onig-regexp/tree/kazuho/untar-onigmo), but the issue is that [on Windows Onigmo cannot be built in a directory other than the `srcdir`](https://github.com/kazuho/mruby-onig-regexp/blob/kazuho/untar-onigmo/mrbgem.rake#L53) (note: on Un*x, we can call `configure` from a different directory).

All in all I'm fine with the latest mruby-onig-regexp; thank you @take-cheeze & @mattn !

**Pull request merged**
